#!/bin/sh
set -e

# Configuration
SCHEMA_DIR="/opt/schema"
BUILD_ORDER="${SCHEMA_DIR}/00_build_order.sql"
TEMP_SQL="/tmp/full_schema.sql"

echo "==> 🛡️  eCTD Internal Bootloader (Alpine)"
echo "    Reading schema from: $SCHEMA_DIR"

if [ ! -f "$BUILD_ORDER" ]; then
    echo "❌ Error: Build order file not found at $BUILD_ORDER"
    exit 1
fi

# 1. Assemble the SQL File
# We iterate through the build order and resolve @include directives
echo "--> 🏗️  Assembling Schema..."
echo "-- Auto-generated by bootstrap.sh" > "$TEMP_SQL"

while IFS= read -r line || [ -n "$line" ]; do
    # Check if line starts with "-- @include"
    # We use grep to check patterns safely in Alpine
    if echo "$line" | grep -q "^-- @include"; then
        # Extract the filepath (remove the prefix)
        include_rel=$(echo "$line" | sed 's/^-- @include //g' | tr -d '\r')
        include_path="${SCHEMA_DIR}/${include_rel}"

        if [ -f "$include_path" ]; then
            echo "    + Including: $include_rel"
            cat "$include_path" >> "$TEMP_SQL"
            echo "" >> "$TEMP_SQL" # Ensure newline
        else
            echo "    ⚠️  WARNING: File not found: $include_path"
        fi
    else
        # Append normal line
        echo "$line" >> "$TEMP_SQL"
    fi
done < "$BUILD_ORDER"

# 2. Execute against the DB
# In docker-entrypoint-initdb.d, we are already connected as the superuser
echo "--> 🚀 Applying Schema to Database..."
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" -f "$TEMP_SQL"

echo "✅ Database Bootstrapped Successfully."
